### PR TITLE
Update and fix custom mek ore processing script.

### PR DESCRIPTION
**Pull request by plapik**
Update kjs custom ore processing script so it works with new mekanism, and add just dire things metals processing.

### CODE REVIEW

**Comment by djnifos** [comment]
Our ATO metals already worked, besides for the JDT stuff, what problem are we trying to fix here?

**Comment by plapik** [comment]
Some parts of script were outdated and simply didn't work. For example recipe slurry output was replaced with chemical one, outdated AlmostUnified method call (getPreferredItemForTag -> getTagTargetItem). Only reason why kubejs didn't show errors was fact that script was unused.

**Comment by djnifos** [comment]
I guess my thoughts are that since the ores from ATO were already working, and we fixed the ATM ores last night, the entire script isn't necessary

**Comment by plapik** [comment]
If it isn't necessary, then please close this PR. Though it may be useful for mods added in future - for example this script was used for silent gear ores in previous ATM.

**Comment by whatthedrunk** [comment]
Thanks a ton for the PR but will close it as asked.

**Pull request closed without merging**
