### PR TITLE
Have Withers drop Cognizant Dust

### LINKED ISSUE #403: [Bug]: Cognizant Dust wont drop.
### Possible Fixes

Yes

### Modpack Version

0.45

### What happened?

I have a Supremium Sword enchanted with Mystical Enlightenment V but when I kill the wither with it then it doesn't drop any Cognizant Dusk. From my understanding, it is supposed to be a Guaranteed drop.

### latest.log

_No response_

### Developer reports

_No response_

### PR DESCRIPTION
**Pull request by thomasvvugt**
Fixes #403

### CODE REVIEW

**Comment by Squtzy** [comment]
Sorry for commenting on a old PR but was this actually fixed? Because I have ATM10 Version 2.20 and the wither setting is still set to false despite the quest book saying still that both the wither and end dragon will drop it.

**Comment by TheBedrockMaster** [comment]
They should both drop it as long as you have the enchantment on your sword, maybe try copying the file from here into your instance and seeing if that works.

**Comment by Squtzy** [comment]
> They should both drop it as long as you have the enchantment on your sword, maybe try copying the file from here into your instance and seeing if that works.

I went into the files and manually edited the line like in one of the issues this was mentioned for. Now it works (If using the enchant ofc). The files was still set to false on wither drops for the Cognizant Dust

**Comment by TheBedrockMaster** [comment]
I’ll test it out later, thanks.

**Pull request merged**
