### PR TITLE
Mek processing stuff

### PR DESCRIPTION
**Pull request by Satherov**
- fixes the `ore processing` overwrite script
- buffs the `solar neutron activator` and `isotopic centrifuge` to their intended numbers

### CODE REVIEW

**Comment by AlphaP2712** [comment]
Im track down to this Merge , I'm not sure it intentional or not but this merge change tier 4 ore processing (that use chemical dissolution Chember) going from 5x to 1.5x by make  washer use 5mb of dirty and output only 3mb ,and use 2 crytral to make 1 shard, after follow the chain processing , output for raw ore is (in/out)(3:4.5) , while tier 3 (that start from Chemical Injection) still output at 4x (in/out)(3:12)

**Comment by Satherov** [comment]
@AlphaP2712 There have been some other changes in other commits, but these are the new numbers for mekanism ore processing 

image

**Comment by AlphaP2712** [comment]
I'm in version 2.8 ,follow the table, I think I found the problem 
image
this step should be 1 crystal make 2 shard?  in this version it 2 crystal make 1 shard.

**Comment by AlphaP2712** [comment]
confirm in creative mode , both JEI and real processing , 2 crystal make 1 shard.

**Comment by Satherov** [comment]
fixed in 4a880db😅

**Comment by AlphaP2712** [comment]
Thank you ^ ^

**Pull request merged**
